/**
 *  Xgen
 *  Copyright (c) John Sundell 2017
 *  Licensed under the MIT license. See LICENSE file.
 */

import Foundation

/// Protocol that objects that can be generated by Xgen conforms to
public protocol Generatable {
    /**
     *  Generate the object into the entity that it represents
     *
     *  Calling this method will generate a file system item for the
     *  object, as specified by its `path`. Further configuration of
     *  the object will not be reflected in the file system, until this
     *  method is called again.
     *
     *  For example, calling this on a `Playground` generates a `.playground`
     *  for its specified configuration.
     *
     *  - throws: `XgenError` if the operation couldn't be completed
     */
    func generate() throws
}
